### PR TITLE
Make ThreeWay support diff engine

### PR DESCRIPTION
**Pull request by michael-o**
Until now ThreeWay internally selected the diff engine although the decision might not be best. Now the developer can select like with other differs.

### CODE REVIEW

**Comment by ralflang** [comment]
I have had a closer look at this. For the lib/ (conservative) path, we should move the engine decision to the back and give it a default.

For the src/ (modern) path, this is all wrong in concept.

Neither ThreeWay nor Diff should create the engine in the constructor but pass it in. 

This would also eliminate the need for pulling in Horde_String and would leave exactly one other reason to depend on Horde_Util (temp files for the shell engine). That is an issue to solve another day ;)

This solves another problem: The StringEngine's diff method has a different signature. Why? Because we mix the "create the diff object graph" concern with the "load data into the diff engine" concern.

**Comment by michael-o** [comment]
Let me crunch on this tomorrow

**Comment by ralflang** [comment]
You may want to have a look at the changes I made to the ThreeWay in lib/

```
     * @param string|Engine $engine Either 'auto' or a Fully Qualified Class Name, a shorthand or an object.
     */
    public function __construct($orig = null, $final1 = null, $final2 = null, $engine = 'auto')
    {
        if (!is_object($engine)) {
            $class = 'Horde_Text_Diff_Engine_';
            if ($engine == 'auto') {
                $class .= extension_loaded('xdiff') ? 'Xdiff' : 'Native';
            } elseif (strpos($engine, '_') === false && strpos($engine, '\\') === false) {
                $class .= Horde_String::ucfirst(basename($engine));
            } else {
                $class = $engine;
            }
            $engine = new $class();
        }
```
and the equivalent in Diff

```
    public function __construct($engine, $params)
    {
        if (!is_object($engine)) {
            $class = 'Horde_Text_Diff_Engine_';
            if ($engine == 'auto') {
                $class .= extension_loaded('xdiff') ? 'Xdiff' : 'Native';
            } elseif (strpos($engine, '_') === false && strpos($engine, '\\') === false) {
                $class .= Horde_String::ucfirst(basename($engine));
            } else {
                $class = $engine;
            }
            $engine = new $class();
        }
        $this->_edits = call_user_func_array(array($engine, 'diff'), $params);
    }
```

I hope this does what you want.

The src/ implementation went a little further than I originally thought. Not only should the Differ not create its engine, it should also not have it - all the engine does is provide a list of operations to the differ. So let's just insert that list.

I think you are in a hurry to move forward with PHP 8.2 compat - in this case just consume the lib/ path. I will make a new alpha release once we are settled.

**Comment by michael-o** [comment]
I left a comment at: https://github.com/maintaina-com/Text_Diff/commit/499f48db5937a62a7921b361a53eef9dd04c9e26#r83924929

I will go with lib/ for the time being because I don't want to rewrite too much code for now without any benefit for my downstream project.

But generally, I like the idea in lib/. Makes sense to me.

**Comment by ralflang** [comment]
I see your argument and I am open to a PR, see below

It is a constructor. As such it is excluded from any implied signature inheritance. While the signature difference between diff() in array-based and string-based engines is an issue that src/ strives to fix, signature differences between constructors are to be expected. Besides, the constructors do already differ. If anything, I would argue for backward compatibility for existing users of the lib/ tree. Upgrades to lib/ should be mostly straight-forward. The engine selection feature is a retrofit, thus it must be optional and intentional.

One can argue for a hybrid constructor, i.e. shift all arguments back one item if the first item is a string. You gain similarity to Diff but these are painful to maintain.

I need to go for a walk and consider.

**Comment by ralflang** [comment]
Superseded by PR #7

**Pull request closed without merging**
