### PR TITLE
Mark EngineTest#testXdiffEngine() as incomplete

### PR DESCRIPTION
**Pull request by michael-o**
Xdiff impl does not support Op_Changed, but only Op_Delete/Op_Add.

### CODE REVIEW

**Comment by ralflang** [comment]
On a logical level, the Xdiff driver treats changes as an add and a delete.
Do you have a set of data where xdiff_string_diff returns anything that cannot be represented by Add and Delete ops?
If the driver is a producer of ops and not a consumer of ops, it is not incomplete as long as it can produce a faithful expression of the change. It would be incomplete if the driver cannot represent an output of xdiff. Which I cannot test currently.

On a technical level:
How did you verify this? I tried to add xdiff to the unit test setup:
https://github.com/maintaina-com/Text_Diff/actions/runs/3052432245/jobs/4921816399
My default distribution also does not have it... I will likely need to create a package to make development more convenient.

**Comment by michael-o** [comment]
This is what the unit test says:
```
1) Horde\Text\Diff\Test\EngineTest::testXdiffEngine
Failed asserting that 4 matches expected 3.
```
and here is the failure because it expects else: https://github.com/maintaina-com/Text_Diff/pull/6/files#diff-ca12e1779899cbc1d32d9fdf374e741f0299df4ccbc427a4a88d7814ef980910L29

**Comment by michael-o** [comment]
My setup:
```
root@deblndw013x3j:/usr/local/www/websvn-dev (php-8.x *=)
# php --info
phpinfo()
PHP Version => 8.2.0beta2

System => FreeBSD deblndw013x3j.ad001.siemens.net 12.3-STABLE FreeBSD 12.3-STABLE GENERIC amd64
Build Date => Sep  9 2022 17:06:59
Build System => FreeBSD deblndw013x3j.ad001.siemens.net 12.3-STABLE FreeBSD 12.3-STABLE GENERIC amd64
Configure Command =>  './configure'  '--disable-all' '--program-prefix=' '--with-config-file-scan-dir=/usr/local/etc/php' '--with-layout=GNU' '--with-libxml' '--with-openssl' '--with-password-argon2=/usr/local' '--disable-cgi' '--enable-dtrace' '--enable-embed' '--enable-fpm' '--with-fpm-group=www' '--with-fpm-user=www' '--prefix=/usr/local' '--localstatedir=/var' '--mandir=/usr/local/man' '--infodir=/usr/local/share/info/' '--build=amd64-portbld-freebsd12.3' 'build_alias=amd64-portbld-freebsd12.3' 'PKG_CONFIG=pkgconf' 'PKG_CONFIG_LIBDIR=/var/tmp/freebsd-ports-head/lang/php82/work/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig' 'CFLAGS=-O2 -pipe -fstack-protector-strong -fno-strict-aliasing ' 'LDFLAGS=-L/usr/lib -lcrypto -lssl -fstack-protector-strong ' 'CPP=cpp' 'CXXFLAGS=-O2 -pipe -fstack-protector-strong -fno-strict-aliasing ' 'OPENSSL_CFLAGS=-I/usr/include' 'OPENSSL_LIBS=-L/usr/lib -lssl -lcrypto'
...
xdiff

xdiff support => enabled
extension version => 2.1.0
libxdiff version => LibXDiff v0.23 by Davide Libenzi <davide@xmailserver.org>
...
...

**Comment by ralflang** [comment]
I see. I agree, this text (and its src/ equivalent) must be marked incomplete until it it tests for the correct thing: The semantics of the diff, not its structure of building blocks.

**Pull request merged**
